[[news]]
date = "2026-05"
content = "以第二作者完成论文 Ctrl-MAR，投稿于 IEEE Transactions on Medical Imaging。"

[[news]]
date = "2026-02"
content = "以共一第二作者完成论文 DA-SAM，投稿于 MICCAI。"

[[news]]
date = "2025-11"
content = "参与完成 CT 超分辨率重建工作，论文投稿至 IEEE Transactions on Medical Imaging 并处于大修状态。"

[[news]]
date = "2025"
content = "获得 2025-2026 学年国家奖学金。"
